### ISSUE TITLE
Jsonb support for Hibernate in spring boot 2.0.1

### ISSUE THREAD

**Issue by rtisma** [velo/hibernate-native-json#11]
Using spring boot 2.0.1 and following the instructions in the read me, the following error occurs

```
java.lang.AbstractMethodError: com.marvinformatics.hibernate.json.JsonUserType.nullSafeSet(Ljava/sql/PreparedStatement;Ljava/lang/Object;ILorg/hibernate/engine/spi/SharedSessionContractImplementor;)V

	at org.hibernate.type.CustomType.nullSafeSet(CustomType.java:160)
	at org.hibernate.persister.entity.AbstractEntityPersister.dehydrate(AbstractEntityPersister.java:2715)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3009)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3533)
	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:89)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:600)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:474)
```

The simple fix is to just overload with the missing methods
```
public class CustomJsonType extends JsonUserType {

  public Object nullSafeGet(ResultSet rs, String[] names, SharedSessionContractImplementor session, Object owner) throws HibernateException, SQLException {
    return nullSafeGet(rs, names, (SessionImplementor) session, owner);
  }

  public void nullSafeSet(PreparedStatement st, Object value, int index, SharedSessionContractImplementor session) throws HibernateException, SQLException {
    nullSafeSet(st, value, index, (SessionImplementor) session);
  }

}
```

**Comment by rtisma** [comment]
version 4.0 depends on hibernate-core 4.2.21-Final, which does not have the `SharedSessionContractImplementor` class.  Spring boot 2.0.1 uses hibernate-core 5.2.16-Final, and has this class

**Comment by velo** [comment]
This may be a good time to move from hibernate 4 to 5.

**Comment by rtisma** [comment]
I have forked and made the changes. In about 20min ill make a PR :) thank
you for your code
